'use strict';
const DAY=86400000;
const ANCHOR=Date.UTC(2026,8,13);
const phase=ms=>((Math.round((ms-ANCHOR)/DAY)%4)+4)%4;
const isWork=ms=>phase(ms)>=2;
function moscowToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=t=>Number(parts.find(p=>p.type===t).value);return Date.UTC(get('year'),get('month')-1,get('day'));}
const fmt=(ms,options)=>new Intl.DateTimeFormat('ru-RU',{...options,timeZone:'UTC'}).format(new Date(ms));
const upper=s=>s.charAt(0).toUpperCase()+s.slice(1);
let today=moscowToday(),month=new Date(today).getUTCMonth(),year=new Date(today).getUTCFullYear();
const el=id=>document.getElementById(id);
function render(){const p=phase(today);el('todayTitle').textContent=isWork(today)?'Сегодня рабочий день':'Сегодня выходной';el('todayDetail').textContent=upper(fmt(today,{weekday:'long',day:'numeric',month:'long'}))+' · '+(p%2===0?'Первый':'Второй')+' '+(isWork(today)?'рабочий день':'выходной')+' из двух';let next=today+DAY;while(!isWork(next))next+=DAY;el('nextWork').textContent=fmt(next,{day:'numeric',month:'long'});const first=Date.UTC(year,month,1),count=new Date(Date.UTC(year,month+1,0)).getUTCDate(),offset=(new Date(first).getUTCDay()+6)%7;el('monthTitle').textContent=upper(fmt(first,{month:'long',year:'numeric'}).replace(' г.',''));let work=0;for(let d=0;d<count;d++)if(isWork(first+d*DAY))work++;el('monthStats').textContent=`Рабочих: ${work} · Выходных: ${count-work}`;el('days').replaceChildren();const cells=Math.ceil((offset+count)/7)*7;for(let i=0;i<cells;i++){const ms=first+(i-offset)*DAY,date=new Date(ms),off=!isWork(ms),item=document.createElement('div');item.className='day'+(off?' off':'')+(date.getUTCMonth()!==month?' other':'')+(ms===today?' current':'');item.setAttribute('aria-label',fmt(ms,{day:'numeric',month:'long',year:'numeric'})+', '+(off?'выходной':'рабочий')+(ms===today?', сегодня':''));if(ms===today)item.setAttribute('aria-current','date');const num=document.createElement('span');num.className='number';num.textContent=date.getUTCDate();const label=document.createElement('span');label.className='day-label';label.textContent=off?'Выходной':'Рабочий';item.append(num,label);el('days').append(item);}el('upcoming').replaceChildren();for(let i=0;i<8;i++){const ms=today+i*DAY,item=document.createElement('div');item.className='upcoming-item'+(!isWork(ms)?' off':'');const caption=document.createElement('span');caption.textContent=i===0?'Сегодня':upper(fmt(ms,{weekday:'short'}));const date=document.createElement('strong');date.textContent=fmt(ms,{day:'numeric',month:'short'});const label=document.createElement('span');label.textContent=isWork(ms)?'Рабочий':'Выходной';item.append(caption,date,label);el('upcoming').append(item);}}
function move(n){const date=new Date(Date.UTC(year,month+n,1));year=date.getUTCFullYear();month=date.getUTCMonth();render();}
el('prev').onclick=()=>move(-1);el('next').onclick=()=>move(1);el('today').onclick=()=>{today=moscowToday();year=new Date(today).getUTCFullYear();month=new Date(today).getUTCMonth();render();};
function refreshDate(){const now=moscowToday();if(now!==today){today=now;render();}}document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshDate();});setInterval(refreshDate,60000);render();
